manifest:
  defaults:
    revision: v3.0
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/onikubimi

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
