manifest:
  defaults:
    revision: v0.3
  # revision: main
  remotes:
    - name: zmkfirmware
    # url-base: https://github.com/onikubimi
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
