manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/onikubimi

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
